# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Klin's Blog
email: mi-cheng@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
    我的blog，记录各种关于技术小文章，欢迎讨论和指正。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KlinLike.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KlinLike

# Build settings
theme: texture
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




# ----------------------------------------------------
# Texture Theme Settings (Texture 主题专属设置)
# ----------------------------------------------------
texture:
  # Title for the blog index page.
  # 博客主页的标题
  title: Klin's Blog

  # Tagline for the blog index page.
  # 主页的标语或副标题
  tagline: 记录各种关于技术小文章

  # Show the texture picker.
  # (可以在页面右下角切换背景纹理，很有趣)
  showPicker: true

  # Post unique share links to social networks
  # (文章底部的分享链接)
  shareLinks: true

  # Enable Disqus comments
  # (Disqus 评论系统)
  disqus_shortname:

  # Enable Google Analytics
  # (谷歌分析)
  google_analytics:

  # Navigation links
  # (导航链接)
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"
    # - title: My Work # 您可以取消注释并添加更多页面
    #   url: "/my-work"

  # Styles ('yellow', 'red', 'black', 'blue', 'green', 'purple')
  style: black

  # Background image for the homepage
  # (主页的背景图片，可以使用 Unsplash 的随机图片服务)
  background_image: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"